[package]
name = "ownership"
version = "0.1.0"
authors = ["Juan Camilo Cardenas Gomez <juaccardenasgom@unal.edu.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
